[project]
name = "parkvision"
version = "0.1.0"
description = "Sistema de gestión de estacionamiento con visión por computadora"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ultralytics>=8.3.243",
]
